// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GeneratePPT(arg1:string,arg2:string):Promise<string>;

export function GetStyleDetail(arg1:string):Promise<main.StyleSkill>;

export function Greet(arg1:string):Promise<string>;

export function ListStyles():Promise<Array<main.StyleCatalogItem>>;

export function LoadConfig():Promise<main.AIConfig>;

export function SaveConfig(arg1:main.AIConfig):Promise<string>;
