package styles

import (
	"fmt"
)

// Style 风格定义
type Style struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Theme       string   `json:"theme"`
	Background  string   `json:"background"`
	Palette     []string `json:"palette"`
	TitleStyle  string   `json:"title_style"`
	LayoutMotif string   `json:"layout_motif"`
	ChartStyle  string   `json:"chart_style"`
	ShapeLang   string   `json:"shape_language"`
	Prompt      string   `json:"prompt"`
}

// BuiltinStyles 内置风格
var BuiltinStyles = map[string]Style{
	"minimal-white": {
		ID:          "minimal-white",
		Name:        "极简白",
		Description: "简洁干净的白色风格，适合商务演示",
		Category:    "内置",
		Theme:       "clean minimal white",
		Background:  "纯白背景 #FFFFFF",
		Palette:     []string{"#FFFFFF", "#F9FAFB", "#111827", "#3B82F6", "#10B981"},
		TitleStyle:  "text-5xl font-bold text-gray-900",
		LayoutMotif: "简洁留白，左对齐或居中",
		ChartStyle:  "简洁线条图，低饱和度",
		ShapeLang:   "细边框，圆角8px",
		Prompt:      "极简白色风格：使用白色和浅灰色背景，深灰色文字，蓝色或绿色作为强调色。",
	},
	"cyber-neon": {
		ID:          "cyber-neon",
		Name:        "赛博霓虹",
		Description: "未来科技感的霓虹风格",
		Category:    "内置",
		Theme:       "futuristic cyber neon",
		Background:  "深色背景配霓虹渐变 #0F172A",
		Palette:     []string{"#0F172A", "#1E293B", "#06B6D4", "#8B5CF6", "#EC4899", "#22D3EE"},
		TitleStyle:  "text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-500",
		LayoutMotif: "网格布局，霓虹边框",
		ChartStyle:  "发光效果的霓虹图表",
		ShapeLang:   "发光边框，渐变填充",
		Prompt:      "赛博霓虹风格：使用深色背景配霓虹色彩，渐变文字，发光边框效果。",
	},
	"bauhaus": {
		ID:          "bauhaus",
		Name:        "包豪斯",
		Description: "德国包豪斯风格，几何与功能主义",
		Category:    "内置",
		Theme:       "bauhaus geometric functionalism",
		Background:  "米色或白色背景",
		Palette:     []string{"#FFFFFF", "#F5F5DC", "#E53935", "#1E88E5", "#FDD835", "#43A047"},
		TitleStyle:  "text-5xl font-bold text-gray-900 uppercase tracking-wider",
		LayoutMotif: "几何网格，功能分区",
		ChartStyle:  "几何形状图表",
		ShapeLang:   "几何形状，圆形方形三角形",
		Prompt:      "包豪斯风格：使用几何形状，原色（红黄蓝），大字体，强调功能性和简洁性。",
	},
	"japanese-minimal": {
		ID:          "japanese-minimal",
		Name:        "日式简约",
		Description: "日式极简美学",
		Category:    "内置",
		Theme:       "japanese zen minimal",
		Background:  "米色或淡粉色背景 #FBF7F4",
		Palette:     []string{"#FBF7F4", "#2C2C2C", "#C4A484", "#8B7355", "#D4C4B0"},
		TitleStyle:  "text-5xl font-light text-gray-800 tracking-wide",
		LayoutMotif: "大量留白，非对称布局",
		ChartStyle:  "水墨风格图表",
		ShapeLang:   "细线条，大量留白",
		Prompt:      "日式简约风格：使用米色或淡粉色背景，深棕色文字，大量留白，细腻的线条装饰。",
	},
	"corporate-blue": {
		ID:          "corporate-blue",
		Name:        "企业蓝",
		Description: "专业的企业蓝色调",
		Category:    "内置",
		Theme:       "professional corporate blue",
		Background:  "白色或浅蓝色背景",
		Palette:     []string{"#FFFFFF", "#EFF6FF", "#1E40AF", "#3B82F6", "#60A5FA", "#1E3A8A"},
		TitleStyle:  "text-5xl font-bold text-blue-900",
		LayoutMotif: "标准商务布局",
		ChartStyle:  "专业商务图表",
		ShapeLang:   "蓝色边框，白色卡片",
		Prompt:      "企业蓝色风格：使用白色和浅蓝色背景，深蓝色文字，专业商务风格。",
	},
	"nature-green": {
		ID:          "nature-green",
		Name:        "自然绿",
		Description: "清新自然的绿色主题",
		Category:    "内置",
		Theme:       "fresh natural green",
		Background:  "白色或淡绿色背景",
		Palette:     []string{"#FFFFFF", "#F0FDF4", "#166534", "#22C55E", "#86EFAC", "#14532D"},
		TitleStyle:  "text-5xl font-bold text-green-900",
		LayoutMotif: "自然流动的布局",
		ChartStyle:  "自然色彩图表",
		ShapeLang:   "圆润的绿色边框",
		Prompt:      "自然绿色风格：使用白色和淡绿色背景，深绿色文字，清新自然的感觉。",
	},
	"dark-tech": {
		ID:          "dark-tech",
		Name:        "暗黑科技",
		Description: "深色科技风格",
		Category:    "内置",
		Theme:       "dark tech futuristic",
		Background:  "纯黑或深灰背景 #0A0A0A",
		Palette:     []string{"#0A0A0A", "#171717", "#404040", "#22D3EE", "#A855F7", "#FFFFFF"},
		TitleStyle:  "text-5xl font-bold text-white",
		LayoutMotif: "全屏布局，科技网格",
		ChartStyle:  "暗色调发光图表",
		ShapeLang:   "细边框，透明效果",
		Prompt:      "暗黑科技风格：使用纯黑或深灰背景，白色文字，细边框和透明效果。",
	},
	"retro-warm": {
		ID:          "retro-warm",
		Name:        "复古暖色",
		Description: "温暖的复古色调",
		Category:    "内置",
		Theme:       "retro warm vintage",
		Background:  "米色或暖白背景 #FFF8F0",
		Palette:     []string{"#FFF8F0", "#2D2A26", "#D97706", "#DC2626", "#059669", "#7C3AED"},
		TitleStyle:  "text-5xl font-bold text-amber-900",
		LayoutMotif: "经典居中布局",
		ChartStyle:  "暖色调图表",
		ShapeLang:   "金色边框，暖色装饰",
		Prompt:      "复古暖色风格：使用米色背景，琥珀色和暖色系文字，复古装饰元素。",
	},
	"elegant-purple": {
		ID:          "elegant-purple",
		Name:        "优雅紫",
		Description: "高贵的紫色主题",
		Category:    "内置",
		Theme:       "elegant purple luxury",
		Background:  "白色或淡紫背景",
		Palette:     []string{"#FFFFFF", "#FAF5FF", "#7C3AED", "#A855F7", "#C084FC", "#581C87"},
		TitleStyle:  "text-5xl font-bold text-purple-900",
		LayoutMotif: "优雅对称布局",
		ChartStyle:  "紫色渐变图表",
		ShapeLang:   "紫色渐变边框",
		Prompt:      "优雅紫色风格：使用白色和淡紫色背景，深紫色文字，高贵优雅的感觉。",
	},
	"ocean-blue": {
		ID:          "ocean-blue",
		Name:        "海洋蓝",
		Description: "清新的海洋主题",
		Category:    "内置",
		Theme:       "fresh ocean blue",
		Background:  "白色或浅蓝背景",
		Palette:     []string{"#FFFFFF", "#F0F9FF", "#0369A1", "#0EA5E9", "#38BDF8", "#023E8A"},
		TitleStyle:  "text-5xl font-bold text-sky-900",
		LayoutMotif: "波浪式布局",
		ChartStyle:  "海洋色彩图表",
		ShapeLang:   "蓝色圆角边框",
		Prompt:      "海洋蓝色风格：使用白色和浅蓝色背景，深蓝色文字，清新海洋的感觉。",
	},
	"sunset-orange": {
		ID:          "sunset-orange",
		Name:        "日落橙",
		Description: "温暖的日落色调",
		Category:    "内置",
		Theme:       "warm sunset orange",
		Background:  "白色或暖白背景",
		Palette:     []string{"#FFFFFF", "#FFFBEB", "#C2410C", "#F97316", "#FDBA74", "#9A3412"},
		TitleStyle:  "text-5xl font-bold text-orange-900",
		LayoutMotif: "温暖渐变布局",
		ChartStyle:  "橙色调图表",
		ShapeLang:   "橙色渐变边框",
		Prompt:      "日落橙色风格：使用白色和暖白背景，橙红色文字，温暖日落的感觉。",
	},
	"mint-fresh": {
		ID:          "mint-fresh",
		Name:        "薄荷清新",
		Description: "清新的薄荷绿",
		Category:    "内置",
		Theme:       "mint fresh clean",
		Background:  "白色或薄荷绿背景",
		Palette:     []string{"#FFFFFF", "#F0FDFA", "#0D9488", "#14B8A6", "#5EEAD4", "#115E59"},
		TitleStyle:  "text-5xl font-bold text-teal-900",
		LayoutMotif: "清新网格布局",
		ChartStyle:  "薄荷绿图表",
		ShapeLang:   "薄荷绿边框",
		Prompt:      "薄荷清新风格：使用白色和薄荷绿背景，青绿色文字，清新干净的感觉。",
	},
	"rose-pink": {
		ID:          "rose-pink",
		Name:        "玫瑰粉",
		Description: "温柔的玫瑰粉色",
		Category:    "内置",
		Theme:       "gentle rose pink",
		Background:  "白色或淡粉背景",
		Palette:     []string{"#FFFFFF", "#FFF1F2", "#BE185D", "#EC4899", "#F9A8D4", "#9D174D"},
		TitleStyle:  "text-5xl font-bold text-pink-900",
		LayoutMotif: "柔和居中布局",
		ChartStyle:  "粉色调图表",
		ShapeLang:   "粉色圆角边框",
		Prompt:      "玫瑰粉色风格：使用白色和淡粉色背景，深粉色文字，温柔浪漫的感觉。",
	},
	"slate-professional": {
		ID:          "slate-professional",
		Name:        "专业灰",
		Description: "专业的蓝灰色调",
		Category:    "内置",
		Theme:       "professional slate",
		Background:  "白色或浅灰背景",
		Palette:     []string{"#FFFFFF", "#F8FAFC", "#334155", "#64748B", "#94A3B8", "#1E293B"},
		TitleStyle:  "text-5xl font-bold text-slate-800",
		LayoutMotif: "标准专业布局",
		ChartStyle:  "灰色调图表",
		ShapeLang:   "灰色细边框",
		Prompt:      "专业灰色风格：使用白色和浅灰背景，石板灰色文字，专业严谨的感觉。",
	},
	"nordic-light": {
		ID:          "nordic-light",
		Name:        "北欧光",
		Description: "明亮的北欧风格",
		Category:    "内置",
		Theme:       "nordic bright light",
		Background:  "纯白或淡灰背景",
		Palette:     []string{"#FFFFFF", "#FAFAFA", "#1F2937", "#4B5563", "#9CA3AF", "#E5E7EB"},
		TitleStyle:  "text-5xl font-medium text-gray-800",
		LayoutMotif: "简洁明亮的北欧布局",
		ChartStyle:  "简洁灰色图表",
		ShapeLang:   "极简细线边框",
		Prompt:      "北欧光风格：使用纯白背景，深灰色文字，极简明亮的北欧设计风格。",
	},
	"red-passion": {
		ID:          "red-passion",
		Name:        "红色激情",
		Description: "充满能量的红色主题",
		Category:    "内置",
		Theme:       "energetic red passion",
		Background:  "白色或浅红背景",
		Palette:     []string{"#FFFFFF", "#FEF2F2", "#B91C1C", "#EF4444", "#FCA5A5", "#7F1D1D"},
		TitleStyle:  "text-5xl font-bold text-red-900",
		LayoutMotif: "动感的红色布局",
		ChartStyle:  "红色系图表",
		ShapeLang:   "红色渐变边框",
		Prompt:      "红色激情风格：使用白色和浅红背景，深红色文字，充满能量和激情的感觉。",
	},
	"gold-luxury": {
		ID:          "gold-luxury",
		Name:        "金色奢华",
		Description: "高贵的金色主题",
		Category:    "内置",
		Theme:       "luxurious gold",
		Background:  "黑色或深色背景",
		Palette:     []string{"#000000", "#1C1917", "#D97706", "#F59E0B", "#FCD34D", "#92400E"},
		TitleStyle:  "text-5xl font-bold text-amber-400",
		LayoutMotif: "奢华居中布局",
		ChartStyle:  "金色调图表",
		ShapeLang:   "金色边框和装饰",
		Prompt:      "金色奢华风格：使用黑色背景，金色文字和边框，奢华高贵的感觉。",
	},
	"forest-earth": {
		ID:          "forest-earth",
		Name:        "森林大地",
		Description: "沉稳的大地色系",
		Category:    "内置",
		Theme:       "earthy forest",
		Background:  "米白或淡棕背景",
		Palette:     []string{"#FFFDF7", "#FEF3C7", "#365314", "#65A30D", "#84CC16", "#1A2E05"},
		TitleStyle:  "text-5xl font-bold text-green-950",
		LayoutMotif: "自然森林布局",
		ChartStyle:  "大地色图表",
		ShapeLang:   "自然棕色边框",
		Prompt:      "森林大地风格：使用米白背景，绿色和棕色文字，沉稳自然的感觉。",
	},
	"coffee-brown": {
		ID:          "coffee-brown",
		Name:        "咖啡棕",
		Description: "温暖的咖啡色调",
		Category:    "内置",
		Theme:       "warm coffee brown",
		Background:  "米色或咖啡白背景",
		Palette:     []string{"#FFFDF8", "#FEF3C7", "#78350F", "#92400E", "#D97706", "#451A03"},
		TitleStyle:  "text-5xl font-bold text-amber-950",
		LayoutMotif: "温馨的咖啡馆布局",
		ChartStyle:  "咖啡色调图表",
		ShapeLang:   "棕色圆角边框",
		Prompt:      "咖啡棕色风格：使用米色背景，棕色和金色文字，温馨咖啡馆的感觉。",
	},
	"sky-dream": {
		ID:          "sky-dream",
		Name:        "天空之梦",
		Description: "梦幻的蓝天白云",
		Category:    "内置",
		Theme:       "dreamy sky blue",
		Background:  "白色或天蓝渐变背景",
		Palette:     []string{"#FFFFFF", "#F0F9FF", "#0284C7", "#38BDF8", "#7DD3FC", "#0C4A6E"},
		TitleStyle:  "text-5xl font-bold text-sky-800",
		LayoutMotif: "轻盈的天空布局",
		ChartStyle:  "天蓝色图表",
		ShapeLang:   "浅蓝圆润边框",
		Prompt:      "天空之梦风格：使用白色和天蓝背景，蓝色文字，梦幻轻盈的感觉。",
	},
	"gradient-modern": {
		ID:          "gradient-modern",
		Name:        "渐变现代",
		Description: "现代渐变风格",
		Category:    "内置",
		Theme:       "modern gradient",
		Background:  "渐变背景紫到蓝",
		Palette:     []string{"#FDF4FF", "#FAE8FF", "#8B5CF6", "#3B82F6", "#A855F7", "#6366F1"},
		TitleStyle:  "text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-600 to-blue-600",
		LayoutMotif: "现代渐变布局",
		ChartStyle:  "渐变色彩图表",
		ShapeLang:   "渐变边框效果",
		Prompt:      "渐变现代风格：使用紫色到蓝色的渐变背景，现代感十足的设计。",
	},
	"neon-pink": {
		ID:          "neon-pink",
		Name:        "霓虹粉",
		Description: "炫酷的霓虹粉色",
		Category:    "内置",
		Theme:       "neon pink cyber",
		Background:  "深紫黑色背景",
		Palette:     []string{"#0F0F1A", "#1A1A2E", "#EC4899", "#F472B6", "#DB2777", "#BE185D"},
		TitleStyle:  "text-5xl font-bold text-pink-400",
		LayoutMotif: "霓虹边框布局",
		ChartStyle:  "霓虹粉色图表",
		ShapeLang:   "发光粉色边框",
		Prompt:      "霓虹粉色风格：使用深紫黑背景，粉红色文字和霓虹发光效果。",
	},
	"lavender-dream": {
		ID:          "lavender-dream",
		Name:        "薰衣草紫",
		Description: "浪漫的薰衣草色调",
		Category:    "内置",
		Theme:       "romantic lavender",
		Background:  "淡紫或白色背景",
		Palette:     []string{"#FFFFFF", "#FAF5FF", "#7E22CE", "#A855F7", "#D8B4FE", "#581C87"},
		TitleStyle:  "text-5xl font-bold text-purple-900",
		LayoutMotif: "浪漫柔和布局",
		ChartStyle:  "薰衣草紫图表",
		ShapeLang:   "紫色渐变边框",
		Prompt:      "薰衣草紫色风格：使用淡紫色背景，深紫色文字，浪漫梦幻的感觉。",
	},
	"earthy-terracotta": {
		ID:          "earthy-terracotta",
		Name:        "赤陶土",
		Description: "复古的陶土色系",
		Category:    "内置",
		Theme:       "terracotta vintage",
		Background:  "米白或淡橙背景",
		Palette:     []string{"#FFF8F0", "#FEF3C7", "#C2410C", "#EA580C", "#FB923C", "#9A3412"},
		TitleStyle:  "text-5xl font-bold text-orange-950",
		LayoutMotif: "复古陶土布局",
		ChartStyle:  "陶土色图表",
		ShapeLang:   "棕色陶土边框",
		Prompt:      "赤陶土风格：使用米白背景，橙红色和棕色文字，复古陶土的感觉。",
	},
	"teal-mystic": {
		ID:          "teal-mystic",
		Name:        "青绿神秘",
		Description: "神秘的青绿色调",
		Category:    "内置",
		Theme:       "mystic teal",
		Background:  "深色或青绿背景",
		Palette:     []string{"#042F2E", "#134E4A", "#0D9488", "#14B8A6", "#2DD4BF", "#115E59"},
		TitleStyle:  "text-5xl font-bold text-teal-200",
		LayoutMotif: "神秘深色布局",
		ChartStyle:  "青绿色图表",
		ShapeLang:   "青绿发光边框",
		Prompt:      "青绿神秘风格：使用深青绿背景，浅青色文字，神秘高级的感觉。",
	},
	"cherry-blossom": {
		ID:          "cherry-blossom",
		Name:        "樱花浪漫",
		Description: "温柔的樱花色调",
		Category:    "内置",
		Theme:       "cherry blossom romance",
		Background:  "淡粉色背景",
		Palette:     []string{"#FFF0F5", "#FDF2F8", "#BE185D", "#EC4899", "#F9A8D4", "#9D174D"},
		TitleStyle:  "text-5xl font-bold text-pink-800",
		LayoutMotif: "浪漫樱花布局",
		ChartStyle:  "粉色樱花图表",
		ShapeLang:   "粉色圆弧边框",
		Prompt:      "樱花浪漫风格：使用淡粉色背景，粉红色文字，浪漫樱花的感觉。",
	},
	"monochrome": {
		ID:          "monochrome",
		Name:        "黑白单色",
		Description: "极简的黑白色调",
		Category:    "内置",
		Theme:       "minimal monochrome",
		Background:  "纯白色背景",
		Palette:     []string{"#FFFFFF", "#F9FAFB", "#111827", "#374151", "#6B7280", "#000000"},
		TitleStyle:  "text-5xl font-black text-black",
		LayoutMotif: "极简黑白布局",
		ChartStyle:  "黑白灰度图表",
		ShapeLang:   "纯黑细线边框",
		Prompt:      "黑白单色风格：使用纯白背景，纯黑文字，极简无色彩的设计。",
	},
	"vibrant-youth": {
		ID:          "vibrant-youth",
		Name:        "活力青春",
		Description: "充满活力的青春色调",
		Category:    "内置",
		Theme:       "vibrant youthful",
		Background:  "白色或亮色背景",
		Palette:     []string{"#FFFFFF", "#F0FDF4", "#16A34A", "#22C55E", "#FACC15", "#15803D"},
		TitleStyle:  "text-5xl font-bold text-green-800",
		LayoutMotif: "活力青春布局",
		ChartStyle:  "多彩活力图表",
		ShapeLang:   "绿色活力边框",
		Prompt:      "活力青春风格：使用白色和亮绿色背景，绿色和黄色文字，充满活力的感觉。",
	},
	"academic-blue": {
		ID:          "academic-blue",
		Name:        "学术蓝",
		Description: "严谨的学术风格",
		Category:    "内置",
		Theme:       "academic scholarly blue",
		Background:  "白色或浅蓝背景",
		Palette:     []string{"#FFFFFF", "#EFF6FF", "#1E3A8A", "#2563EB", "#60A5FA", "#1E40AF"},
		TitleStyle:  "text-5xl font-bold text-blue-950",
		LayoutMotif: "学术严谨布局",
		ChartStyle:  "学术蓝色图表",
		ShapeLang:   "深蓝经典边框",
		Prompt:      "学术蓝色风格：使用白色和浅蓝背景，深蓝色文字，严谨学术的感觉。",
	},
	"startup-modern": {
		ID:          "startup-modern",
		Name:        "创业现代",
		Description: "适合创业公司的现代风格",
		Category:    "内置",
		Theme:       "modern startup",
		Background:  "白色背景配渐变",
		Palette:     []string{"#FFFFFF", "#F8FAFC", "#6366F1", "#8B5CF6", "#A855F7", "#7C3AED"},
		TitleStyle:  "text-5xl font-bold text-indigo-900",
		LayoutMotif: "现代创业布局",
		ChartStyle:  "现代渐变图表",
		ShapeLang:   "紫色现代边框",
		Prompt:      "创业现代风格：使用白色背景，紫色和靛蓝色文字，现代创业的感觉。",
	},
}

// ListStyles 列出所有风格
func ListStyles() []Style {
	styles := make([]Style, 0, len(BuiltinStyles))
	for _, s := range BuiltinStyles {
		styles = append(styles, s)
	}
	return styles
}

// GetStyle 获取指定风格
func GetStyle(id string) (*Style, error) {
	if s, ok := BuiltinStyles[id]; ok {
		return &s, nil
	}
	return nil, fmt.Errorf("风格不存在: %s", id)
}

// GetStyleOrDefault 获取风格，如果不存在则返回默认风格
func GetStyleOrDefault(id string) *Style {
	if s, ok := BuiltinStyles[id]; ok {
		return &s
	}
	defaultStyle := BuiltinStyles["minimal-white"]
	return &defaultStyle
}

// GetStyleNames 获取所有风格名称
func GetStyleNames() []string {
	names := make([]string, 0, len(BuiltinStyles))
	for id := range BuiltinStyles {
		names = append(names, id)
	}
	return names
}
