// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GeneratePPT(arg1, arg2) {
  return window['go']['main']['App']['GeneratePPT'](arg1, arg2);
}

export function GetStyleDetail(arg1) {
  return window['go']['main']['App']['GetStyleDetail'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListStyles() {
  return window['go']['main']['App']['ListStyles']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
